<!DOCTYPE html>
<html lang="es">
<head>
	<title>Crear Cuenta | Marta</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Sistema de gestión de finanzas hogareñas compartidas">

	<!-- <link href="style.css" rel="stylesheet"> -->
	<!-- <link rel="icon" type="image/svg+xml" href="/favicon.svg"> -->
</head>
<body>
	<nav>
		<ul>
			<li><a href="/cuentas">Cuentas</a></li>
		</ul>
	</nav>
	<header>
		<h1>Crear cuenta</h1>
	</header>
	<main>
		<form>
			<label>
				Nombre
				<input type="text" autocomplete="off" autofocus name="nombre">
			</label>
			<label>
				Titulares
				<select multiple name="titulares">
					<option>1</option>
					<option>2</option>
				</select>
			</label>
			<input type="submit">
		</form>
	</main>
	<!-- <script src="script.js"></script> -->
</body>
</html>
