<!DOCTYPE html>
<html lang="es">
<head>
	<title>Cuentas | Marta</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Sistema de gestión de finanzas hogareñas compartidas">
	<base href="/cuentas/">

	<!-- <link href="style.css" rel="stylesheet"> -->
	<!-- <link rel="icon" type="image/svg+xml" href="/favicon.svg"> -->
</head>
<body>
	<nav>
		<ul>
			<li>Cuentas</li>
		</ul>
	</nav>
	<header>
		<h1>Gestión de cuentas</h1>
	</header>
	<main>
		<search>
			<form>
				<label>
					Búsqueda
					<input type="search" autocomplete="on" autofocus name="q">
				</label>
				<input type="submit">
			</form>
		</search>
		<a href="nuevo">Crear cuenta</a>
		<table>
			<caption>
				<h2>Cuentas</h2>
			</caption>
			<thead>
				<tr>
					<th scope="col">Nombre</th>
					<th scope="col">Titulares</th>
					<th scope="col">Acciones</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tbody>
		</table>
	</main>
	<!-- <script src="script.js"></script> -->
</body>
</html>
