<?php
declare(strict_types=1);

use App\Cuentas\Cuenta;
use League\Plates\Template\Template;
use Mezzio\Helper\UrlHelperInterface;

\assert($this instanceof Template);

/** @var ?string */
$query ??= null;
$query = (string) $query;

/** @var ?UrlHelperInterface */
$urlHelper ??= null;
\assert($urlHelper instanceof UrlHelperInterface);

/** @var Cuenta[] */
$cuentas ??= [];
// Verifico que $cuentas este compuesto por elementos de tipo Cuenta
(fn(Cuenta ...$cuentas): array => $cuentas)(...$cuentas);

echo $cuentas[0]->nombre();

?>
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Cuentas | Marta</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Sistema de gestión de finanzas hogareñas compartidas">
	<!-- <link href="style.css" rel="stylesheet"> -->
	<!-- <link rel="icon" type="image/svg+xml" href="/favicon.svg"> -->
</head>
<body>
	<nav>
		<ul>
			<li>Cuentas</li>
		</ul>
	</nav>
	<header>
		<h1>Gestión de cuentas</h1>
	</header>
	<main>
		<search>
			<form>
				<label>
					Búsqueda
					<input type="search" autocomplete="on" autofocus name="q" value="<?= $query ?>">
				</label>
				<input type="submit">
			</form>
			<form>
				<button type="submit">Restablecer</button>
			</form>
		</search>
		<a href="<?= $urlHelper->generate('cuentas.nuevo') ?>">Crear cuenta</a>
		<table>
			<caption>
				<h2>Cuentas</h2>
			</caption>
			<thead>
				<tr>
					<th scope="col">Nombre</th>
					<th scope="col">Titulares</th>
					<th scope="col">Acciones</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($cuentas as $cuenta): ?>
				<tr>
					<td><?= $this->e($cuenta->nombre()) ?></td>
					<td></td>
					<td>
						<a href="<?= $urlHelper->generate('cuentas.edicion', ['id' => $cuenta->id()]) ?>">Editar</a>
					</td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</main>
	<!-- <script src="script.js"></script> -->
</body>
</html>
