<?php
declare(strict_types=1);

use League\Plates\Template\Template;

\assert($this instanceof Template);

$title ??= null;
\assert(is_string($title));

?>
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8" />
	<script src="https://cdn.jsdelivr.net/gh/underground-works/clockwork-browser@1/dist/metrics.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title><?=$this->e($title)?> | Marta</title>
	<meta name="description" content="Sistema de gestión de finanzas hogareñas compartidas">
	<!-- <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
	<link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet" />
	<style>
			body { padding-top: 70px; }
			.app { min-height: 100vh; }
			.app-footer { padding-bottom: 1em; }
			.mezzio-green, h2 a, h2 a:hover { color: #009655; }
			.navbar-brand { padding: 0; }
			.navbar-brand img { margin: -.5rem 0; filter: brightness(0) invert(1); }
	</style> -->
	<!-- <link rel="stylesheet" href="<?= $this->asset('/styles/reset.css') ?>" > -->
	<?php require __DIR__ . '/styles_base.phtml' ?>
	<!-- <?=$this->section('stylesheets')?> -->
	<script src="https://cdn.jsdelivr.net/gh/gnat/css-scope-inline/script.js"></script>
</head>
<body hx-boost="true">
	<?= $this->section('content') ?>
	<?php require __DIR__ . '/scripts_base.phtml' ?>
	<!-- <?=$this->section('javascript')?> -->
</body>
</html>
