<?php


declare(strict_types=1);

use Marta\Presentation\Cuentas\Controllers\CuentasController;
use Mezzio\Helper\UrlHelperInterface;
use Marta\Domain\Cuentas\Cuenta;
use League\Plates\Template\Template;

\assert($this instanceof Template);

/** @var ?Cuenta $cuenta */
$cuenta ??= null;
\assert($cuenta instanceof Cuenta);

?>

<?php $this->layout('layout::default', ['title' => 'Editar Cuenta']) ?>

<?php $this->insert('components::navbar') ?>

<header>
	<h1>Editar cuenta</h1>
</header>
<main>
	<form method="POST" action="<?= $this->url(CuentasController::ACTUALIZAR, ['id' => $cuenta->id()]) ?>">
		<label>
			Nombre (*)
			<input type="text" autocomplete="off" name="nombre" required value="<?= $this->e($cuenta->nombre()) ?>">
		</label>
		<label>
			Titulares
			<select multiple name="titulares">
				<option>1</option>
				<option>2</option>
			</select>
		</label>
		<input type="submit">
	</form>
	<form>
		<button type="submit">Eliminar</button>
	</form>
</main>
