<?php


declare(strict_types=1);

use Marta\Domain\Cuentas\Cuenta;
use League\Plates\Template\Template;
use Marta\Presentation\Cuentas\Controllers\CuentasController;
use Mezzio\Helper\UrlHelperInterface;

// dd($this);

\assert($this instanceof Template);

/** @var ?string $query */
$query ??= null;
\assert(is_string($query));

/** @var Cuenta[] $cuentas */
// Verifico que $cuentas este compuesto por elementos de tipo Cuenta
(fn(Cuenta ...$cuentas): array => $cuentas)(...$cuentas);

?>

<?php $this->layout('layout::default', ['title' => 'Cuentas']) ?>

<?php $this->insert('components::navbar') ?>
<header>
	<h1>Gestión de cuentas</h1>
</header>
<main>
	<search>
		<form action="<?= $this->url(CuentasController::INDICE) ?>">
			<label>
				Búsqueda
				<input type="search" autocomplete="on" autofocus name="q" value="<?= $query ?>">
			</label>
			<input type="submit">
		</form>
		<form action="<?= $this->url(CuentasController::INDICE) ?>">
			<button type="submit">🧹</button>
		</form>
	</search>
	<a href="<?= $this->url(CuentasController::NUEVO) ?>">Crear cuenta</a>
	<table>
		<caption>
			<h2>Cuentas</h2>
		</caption>
		<thead>
			<tr>
				<th scope="col">Nombre</th>
				<th scope="col">Titulares</th>
				<th scope="col">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($cuentas as $cuenta): ?>
			<tr>
				<td><?= $this->e($cuenta->nombre()) ?></td>
				<td></td>
				<td>
					<a href="<?= $this->url(CuentasController::EDICION, ['id' => $cuenta->id()]) ?>">Editar</a>
				</td>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</main>
