<?php


declare(strict_types=1);

use Marta\Domain\Cuentas\Cuenta;
use League\Plates\Template\Template;
use Marta\Presentation\Cuentas\Controllers\CuentasController;

\assert($this instanceof Template);

/** @var ?string $query */
$query ??= null;
\assert(is_string($query));

/** @var Cuenta[] $cuentas */
// Verifico que $cuentas este compuesto por elementos de tipo Cuenta
(fn(Cuenta ...$cuentas): array => $cuentas)(...$cuentas);

?>

<?php $this->layout('layout::default', ['title' => 'Cuentas']) ?>

<?php $this->insert('components::navbar') ?>
<header>
	<h1>Gestión de cuentas</h1>
</header>
<main>
	<?php $this->insert('components::generic-search', ['uri' => $this->url(CuentasController::INDICE), 'query' => $query, 'target' => '[data-resultados=cuentas]']) ?>
	<a href="<?= $this->url(CuentasController::NUEVO) ?>">Crear cuenta</a>
	<section data-resultados="cuentas">
		<?php $this->insert('cuentas::components/indice-tabla', ['cuentas' => $cuentas]) ?>
	</section>
</main>
