<?php


declare(strict_types=1);

use Marta\Presentation\Cuentas\Controllers\CuentasController;
use League\Plates\Template\Template;

\assert($this instanceof Template);

?>

<?php $this->layout('layout::default', ['title' => 'Crear Cuenta']) ?>

<?php $this->insert('components::navbar') ?>

<header>
	<h1>Crear cuenta</h1>
</header>
<main>
	<form
		hx-post="<?= $this->url(CuentasController::CREAR) ?>"
		hx-indicator=".htmx-indicator[name=cuentas-nuevo]"
		hx-push-url="true"
	>
		<label>
			Nombre (*)
			<input type="text" autocomplete="off" autofocus name="nombre" required>
		</label>
		<label>
			Titulares
			<select multiple name="titulares">
				<option>1</option>
				<option>2</option>
			</select>
		</label>
		<input type="submit">
		<?php $this->insert('components::indicator-spin', ['name' => 'cuentas-nuevo']) ?>
	</form>
</main>
